# Generated by Django 5.1.5 on 2025-01-17 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_input_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
